apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: restricted
  labels:
    jenkins: slave
    jenkins/label: dotnetcore31
  name: jenkins-slave-centos7-dotnetcore31-image-wei
  namespace: wei-sandbox
spec:
  containers:
    - command: ["/bin/sh"]
      args: ["-c", "while true; do echo hello; sleep 1000;done"]
      env:
        - name: JENKINS_SECRET
          value: c87f7ed76c53dff1ead3cb4425abc8fb0a55807661d93c0ac8ef7cbbaa4722b2
        - name: JENKINS_TUNNEL
          value: '172.16.223.209:50000'
        - name: JENKINS_AGENT_NAME
          value: jenkins-slave-centos7-dotnetcore31-image-wei
        - name: JENKINS_NAME
          value: jenkins-slave-centos7-dotnetcore31-image-wei
        - name: JENKINS_AGENT_WORKDIR
          value: /tmp
        - name: JENKINS_URL
          value: 'http://172.16.201.116:80/'
      image: >-
        docker-registry.default.svc:5000/wei-sandbox/jenkins-slave-centos7-dotnetcore31-image
      imagePullPolicy: Always
      name: jnlp
      resources: {}
      securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        privileged: false
        runAsUser: 1001660000
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /tmp
          name: workspace-volume
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: jenkins-custom-token-m9qfx
          readOnly: true
      workingDir: /tmp
  dnsPolicy: ClusterFirst
  imagePullSecrets:
    - name: jenkins-custom-dockercfg-f4nhv
  nodeSelector:
    beta.kubernetes.io/os: linux
    node-role.kubernetes.io/compute: 'true'
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1001660000
    seLinuxOptions:
      level: 's0:c41,c10'
  serviceAccount: jenkins-custom
  serviceAccountName: jenkins-custom
  terminationGracePeriodSeconds: 30
  volumes:
    - emptyDir: {}
      name: workspace-volume
    - name: jenkins-custom-token-m9qfx
      secret:
        defaultMode: 420
        secretName: jenkins-custom-token-m9qfx